### ISSUE TITLE
Can't sign in google account

### ISSUE THREAD

**Issue by n0n3n0w** [YihangZhu/LaTeX-in-Google-Spreadsheet#1]
I was trying to install but after i login google, it said this application has not been verified. Hopefully it will be fixed soon. I need to finish my mini thesis. 

Thank you in advanced.

**Comment by YihangZhu** [comment]
> I was trying to install but after i login google, it said this application has not been verified. Hopefully it will be fixed soon. I need to finish my mini thesis.
> 
> Thank you in advanced.

I will verify it. It will take some weeks. Meanwhile, if you want to use the add-on sooner, you can open Tools -> script editor in google spreadsheet and copy my source code to there. Save the script editor and reopen the spreadsheet, you will find the add-on in Add-ons of the spreadsheet.

**Comment by YihangZhu** [comment]
The app has been verified.
