### ISSUE TITLE
underscore in celltext was no auto-escaped

### ISSUE THREAD

**Issue by le-lenn** [YihangZhu/LaTeX-in-Google-Spreadsheet#2]
The exact text in the cell was: 
"Event Name 
(eg. group_name - event)"

This resulted in a compilation error in Latex and I had to escape the underscore manually. Would be amazing if special characters could get escaped automatically!

**Comment by YihangZhu** [comment]
> The exact text in the cell was:
> "Event Name
> (eg. group_name - event)"
> 
> This resulted in a compilation error in Latex and I had to escape the underscore manually. Would be amazing if special characters could get escaped automatically!

Hi, thank you for the suggestion. There are pros and cons by setting them automatically. As I wrote in the readme: "Special LaTeX chars only "%"s are replaced with "\%". The rest special LaTeX chars remain intact, given that they may not be plain text. For example, $x$ may be a mathematical notation." 
But I will try to find a way to improve it.

By the way, by using "replace all" you can easily do the changes manually.

**Comment by le-lenn** [comment]
Thanks for clarifying!
I did not readme carefully enough apparently.

Have a nice day!

**Comment by YihangZhu** [comment]
> The exact text in the cell was:
> "Event Name
> (eg. group_name - event)"
> 
> This resulted in a compilation error in Latex and I had to escape the underscore manually. Would be amazing if special characters could get escaped automatically!

Hi LennardSchwarz
I have adopted your comment in the addon.

**Comment by le-lenn** [comment]
This is awesome!
I’ll check it out, thanks for telling me.

Viele Grüße,
Lennard Schwarz
