### ISSUE TITLE
% in the sheet became \\% in the exported latex

### ISSUE THREAD

**Issue by isarunc** [YihangZhu/LaTeX-in-Google-Spreadsheet#3]
Hello,

Thanks for the awesome add-ons!
I'm using this add-on to export tables, but I found out that the % character is escaped using two slashes (\\%) instead of one (\%).
For example, 10.15% in the google sheet became 10.15\\% in latex, which did not work properly until I changed it to 10.15\% (removed one slash).
Using Find and Replace can solve this problem, but I think I would like to report this regardless.

Cheers!
Isarun

**Comment by YihangZhu** [comment]
Hi Isarunc,
Thank you for pointing out the issue.
I have fixed the bug.

Cheers,
Yihang.

**Comment by YihangZhu** [comment]
> Hello,
> 
> Thanks for the awesome add-ons!
> I'm using this add-on to export tables, but I found out that the % character is escaped using two slashes (\%) instead of one (%).
> For example, 10.15% in the google sheet became 10.15\% in latex, which did not work properly until I changed it to 10.15% (removed one slash).
> Using Find and Replace can solve this problem, but I think I would like to report this regardless.
> 
> Cheers!
> Isarun

Hi Isarunc,
Thank you for pointing out the issue.
I have fixed the bug.

Cheers,
Yihang.
