### ISSUE TITLE
Colors don't seem to work in lowercase?

### ISSUE THREAD

**Issue by orinatic** [YihangZhu/LaTeX-in-Google-Spreadsheet#4]
Hello!

I don't know what combination of packages I'm using that is causing this issue (it might just be me), but it seems like `cellcolor[HTML]{<color>}` only works when <color> is capitalized. Is there any chance you either have any idea what's wrong with my setup or else could export colors capitalized instead of lowercase?

**Comment by YihangZhu** [comment]
Hi, 
I don't have that problem. Do you mean it should be Cellcolor? 
Have you used the package :%\usepackage[table]{xcolor} % for cell colors

Cheers, 
Yihang.
