### ISSUE TITLE
percent charactor (%) is not escaped in header

### ISSUE THREAD

**Issue by mlzxy** [YihangZhu/LaTeX-in-Google-Spreadsheet#5]
It seems not to escape % and therefore creates uncompilable code when % presents and gets interpreted as a comment. 

Great extension and thanks so much for your work.

**Comment by YihangZhu** [comment]
Thanks for your comment. 
It works fine for me. 
Could you share with me the case where it didn't work?
Cheers, 
Yihang.

**Comment by mlzxy** [comment]
Thanks for your quick response!  Please try the excel file attached.
Percent (%) character is not escaped when converting the table within the
border.

The tested browser and os version are: Chrome 101.0.4951.64 / OSX 11.6.5

I appreciate your time.

Best,
Xinyu

**Comment by YihangZhu** [comment]
Hi Xinyu, 
Thank you for your comment. 
I have fixed the bug. 
It should work now. 
Cheers, 
Yihang.
