### ISSUE TITLE
Can't do partial table

### ISSUE THREAD

**Issue by karma-riuk** [YihangZhu/LaTeX-in-Google-Spreadsheet#6]
When selecting an entire table, the extension works perfectly, but when you start un-selecting some columns, the extensions seems to "break".

Let me give an example:

If I have this table, I selected the entire table, then did a Ctrl-click through the C and E columns, my result is a table with only A, B and D columns.
![image](https://github.com/user-attachments/assets/69cf70fe-39ab-4189-a03e-89bbf39e450a)

If I select the 'sheet->Latex' option, this is the result:
```latex
\begin{table}[!htp]\centering
\caption{Generated by Spread-LaTeX}\label{tab: }
\scriptsize
\begin{tabular}{lr}\toprule
D \\\midrule
21 \\
22 \\
23 \\
24 \\
\bottomrule
\end{tabular}
\end{table}
```

Note: the "focused cell" in the picture is the D column title cell. 

If I then un-select and re-select the A column title, to place the "focused cell" in the top left corner, as in the following picture:

![image](https://github.com/user-attachments/assets/89a8296b-d22d-4155-a83a-17966d22bde8)

I get the following output:
```latex
\begin{table}[!htp]\centering
\caption{Generated by Spread-LaTeX}\label{tab: }
\scriptsize
\begin{tabular}{lrr}\toprule
A &B \\\midrule
hello &1 \\
world &2 \\
foo &3 \\
bar &4 \\
\bottomrule
\end{tabular}
\end{table}
```

It seems like the generated table is looking at where the "focused cell" is and not caring about any over selection outside of it.

Would it be possible to add those detached selections? I would like to use it because I have large tables, that fit well in the sheets view, but do not look good in the latex document.

Thanks in advance for your consideration.

Edit:

I didn't mention what my expected output would be, but just to be clear, with the selection in the above pictures, I would like the output the table with only the A, B and D columns:

```latex
\begin{table}[!htp]\centering
    \caption{Generated by Spread-LaTeX}\label{tab: }
    \scriptsize
    \begin{tabular}{lrrrrr}\toprule
        A     & B & D  \\\midrule
        hello & 1 & 21 \\
        world & 2 & 22 \\
        foo   & 3 & 23 \\
        bar   & 4 & 24 \\
        \bottomrule
    \end{tabular}
\end{table}
```

**Comment by karma-riuk** [comment]
After looking into the [sheet class API](https://developers.google.com/apps-script/reference/spreadsheet/sheet), it looks like you might only need to use the [`getActiveRangeList()`](https://developers.google.com/apps-script/reference/spreadsheet/sheet#getActiveRangeList()) function instead of the current `getActiveRange()` at line 15 of the `Sheet2Latex.js` file. The rest of the code might probably need to be slightly updated though.

**Comment by YihangZhu** [comment]
Thanks for your suggestion. Let me check my code.

**Comment by YihangZhu** [comment]
The feature has been added.
